ARG BASE_IMAGE=netboxcommunity/netbox
ARG BASE_IMAGE_VERSION=latest
FROM $BASE_IMAGE:$BASE_IMAGE_VERSION

WORKDIR /opt/netbox/netbox

# Install Doppler CLI
RUN apt-get update && apt-get install -y apt-transport-https ca-certificates curl gnupg && \
      curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | apt-key add - && \
      echo "deb https://packages.doppler.com/public/cli/deb/debian any-version main" | tee /etc/apt/sources.list.d/doppler-cli.list && \
      apt-get update && \
      apt-get -y install doppler

ENTRYPOINT [ "/sbin/tini", "--" ]

# Fetch secrets and exec netbox
CMD ["doppler", "run", "--", "/opt/netbox/docker-entrypoint.sh", "/opt/netbox/launch-netbox.sh"]
