services:
  netbox:
    build:
      context: .
      dockerfile: Dockerfile-plugins
    image: netbox-plugins:v4.4-3.4.0
    restart: unless-stopped
    ports:
      - "8000:8080"

  netbox-worker:
    restart: unless-stopped

  netbox-housekeeping:
    restart: unless-stopped
