FROM ghcr.io/netbox-community/netbox:latest

COPY requirements-plugins.txt /opt/netbox/requirements-plugins.txt

RUN /usr/local/bin/uv pip install --no-cache-dir -r /opt/netbox/requirements-plugins.txt
