FROM ghcr.io/netbox-community/netbox:v4.4-3.4.0

COPY requirements-plugins.txt /opt/netbox/requirements-plugins.txt

RUN /usr/local/bin/uv pip install --no-cache-dir -r /opt/netbox/requirements-plugins.txt
