#!/bin/bash

. hooks/common

if [ "${BUILD}" == "BRANCHES" ]; then
  echo "🐳🐳🐳 Testing"
  export DOCKER_TARGET="main"

  docker-compose pull --parallel
  docker-compose build
  docker-compose run netbox ./manage.py test
else
  echo "🐳🐳🐳 No tests are implemented for build '${BUILD}'."
fi
